version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: qr-project-db
    env_file:
      - .env
    environment:
      LC_ALL: C.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qr-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: qr-project-backend
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 80
      HOST: postgres
    depends_on:
      postgres:
        # CAMBIO: Se usa 'service_started' porque se eliminó el healthcheck
        condition: service_started
    ports:
      - "80:80"
    networks:
      - qr-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: qr-project-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - qr-network
    restart: unless-stopped

networks:
  qr-network:
    driver: bridge

volumes:
  postgres_data: