- name: Conexión SSH y Despliegue
        timeout-minutes: 3
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
          PAT_TOKEN: ${{ secrets.GIT_PAT_TOKEN }}
          GITHUB_USER: tu-usuario-de-github # Reemplaza con tu usuario de GitHub
        run: |
          sshpass -p "$SSH_PASSWORD" ssh \
            -o StrictHostKeyChecking=no \
            -p $SSH_PORT $SSH_USER@$SSH_HOST << EOF

            set -euo pipefail
            
            echo "Navegando al directorio del proyecto: $PROJECT_PATH"
            cd "$PROJECT_PATH"
            
            echo "Contenido del directorio actual:"
            ls -la # <-- AÑADE ESTA LÍNEA PARA DEPURAR
            
            # --- Despliegue del Backend ---
            echo "Desplegando backend..."
            cd backend # El error ocurre aquí
            
            # ... el resto de tu script no cambia ...
            git pull https://$GITHUB_USER:$PAT_TOKEN@github.com/tu-usuario-de-github/nombre-de-tu-repo-backend.git main
            npm install
            echo "Reiniciando servicio pm2 del backend..."
            pm2 restart backend
            
            cd ../frontend
            git pull https://$GITHUB_USER:$PAT_TOKEN@github.com/tu-usuario-de-github/nombre-de-tu-repo-frontend.git main
            npm install
            npm run build
            echo "Reiniciando servicio pm2 del frontend..."
            pm2 restart frontend

          EOF